### ISSUE TITLE
个人用户，可以运行打卡，但是收不到邮件提醒。。。

### ISSUE THREAD

**Issue by 233333LSSSSSSSS** [ClokMuch/ZZUjksbDirect#14]
如题，都设置好了，可以正常打卡，就是没提醒邮件..

**Comment by ClokMuch** [comment]
> 如题，都设置好了，可以正常打卡，就是没提醒邮件..

目前本项目不计划支持成功打卡的邮件提醒，除非调试模式开启，只会在打卡失败后邮件提醒.

如有需要可以参考其他项目的推送服务，比起发送邮件，推送可能更符合需求.
