### ISSUE TITLE
请问城市码是什么？

### ISSUE THREAD

**Issue by LQY0606** [ClokMuch/ZZUjksbDirect#9]

**Comment by ClokMuch** [comment]
> _No description provided._

所述“城市码”一般是对应地区身份证号前4位，也可以自行从jksb平台的表单中审查“选择城市”的下拉列表的 value ，特别地，河南省郑州市对应城市码为 4101 .

如果无后续问题，您可以关闭此 issue ；若您仍需要进一步了解，敬请接续留言 :D

若您长时间无回复，我将关闭此 issue (/▽＼)
